# fly.toml — config per cmh-llm-bridge

app = "cmh-llm-bridge"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 40

  [[http_service.checks]]
    method = "GET"
    path = "/health"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"

# Risorse predefinite per le nuove macchine (puoi aumentare memory_mb se serve)
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512